### ISSUE TITLE
What are the prerequisites for BedWars-0.2.15 + SBAHypixelify v1.4.3?

### ISSUE THREAD

**Issue by rtsai** [pronze/SBA#129]
Using the following server stack:

- Ubuntu
- openjdk version "16.0.1" 2021-04-20
- paper-1.16.5-753.jar  # recent
- BedWars-0.2.15.jar    # latest release from spigotmc
- SBAHypixelify-1.4.3-all.jar    # latest release from spigotmc
- https://github.com/PlaceholderAPI/PlaceholderAPI/releases/download/2.10.9/PlaceholderAPI-2.10.9.jar  # latest
- https://github.com/dmulloy2/ProtocolLib/releases/download/4.6.0/ProtocolLib.jar  # latest

With this combination, SBAHypixelify fails to start; logs attached.

[log1.txt](https://github.com/pronze/SBAHypixelify/files/6602996/log1.txt)

What's weird is towards the end, it looks like BedWars is loading 3 times:

```
[11:01:52 INFO]: [PlaceholderAPI] Successfully registered expansion: bedwars
[11:01:52 INFO]: ================  by ScreamingSandals <Misat11, Ceph>
[11:01:52 INFO]: + BedWars Zero +  Version: 0.2.15
[11:01:52 INFO]: ================  STABLE VERSION
[11:01:52 INFO]: Everything is loaded! If you like our work, consider visiting our Patreon! <3
[11:01:52 INFO]: https://www.patreon.com/screamingsandals
[11:01:52 INFO]: [BedWars] Disabling BedWars v0.2.15
[11:01:52 INFO]: [PlaceholderAPI] Unregistered placeholder expansion: bedwars
[11:01:52 INFO]: [BedWars] Enabling BedWars v0.2.15
[11:01:52 WARN]: Enabled plugin with unregistered PluginClassLoader BedWars v0.2.15
[11:01:52 INFO]: [BedWars] Successfully loaded messages for BedWars! Language: lang_name
[11:01:52 INFO]: [BedWars] Loading statistics from YAML-File ...
[11:01:52 INFO]: [PlaceholderAPI] Successfully registered expansion: bedwars
[11:01:52 INFO]: ================  by ScreamingSandals <Misat11, Ceph>
[11:01:52 INFO]: + BedWars Zero +  Version: 0.2.15
[11:01:52 INFO]: ================  STABLE VERSION
[11:01:52 INFO]: Everything is loaded! If you like our work, consider visiting our Patreon! <3
[11:01:52 INFO]: https://www.patreon.com/screamingsandals
[11:01:52 INFO]: [SBAHypixelify]: &aMade changes to the config.yml file!
[11:01:52 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[11:01:59 ERROR]: Error occurred while enabling SBAHypixelify v1.4.3 (Is it up to date?)
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:828) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:513) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
```

Removing just the SBAHypixelify plugin makes the problem go away.

**Comment by zlataovce** [comment]
known bug, caused by an api change

wait for patch release

**Comment by rtsai** [comment]
Is there a known good combination of plugins/versions? Thank you.

**Comment by pronze** [comment]
SBA v1.5.3 and bw 0.2.18 are a good combination :)
