### ISSUE TITLE
What are the prerequisites for BedWars-0.3.0-SNAPSHOT + SBAHypixelify-2.0.0-SNAPSHOT?

### ISSUE THREAD

**Issue by rtsai** [pronze/SBA#130]
Using the following server stack:

- Ubuntu
- openjdk version "16.0.1" 2021-04-20
- paper-1.16.5-753.jar  # recent
- https://ci.screamingsandals.org/job/BedWars-0.x.x/803  # latest from CI
- https://ci.screamingsandals.org/job/SBAHypixelify/177  # latest from CI

With this combination, SBAHypixelify fails to start; logs attached: [log2.txt](https://github.com/pronze/SBAHypixelify/files/6603009/log2.txt)

The `java.lang.ClassNotFoundException: org.screamingsandals.bedwars.lib.material.Item` makes me wonder whether CI is properly building the snapshot JAR files, since I do see `Item.class` in the JAR file, or maybe I'm missing some other plugin file. It seems to be part of ScreamingLib, but the CI server doesn't have any downloads for that project

```
[11:18:46 INFO]: Time elapsed: 1125 ms
[11:18:46 INFO]: [BedWars] Enabling BedWars v0.3.0-SNAPSHOT
[11:18:46 INFO]: [BedWars] Loading statistics from YAML-File ...
[11:18:46 INFO]: =====================  by ScreamingSandals <Misat11, Iamceph, Pronze>
[11:18:46 INFO]: + Screaming BedWars +  Version: 0.3.0-SNAPSHOT FREE
[11:18:46 INFO]: =====================  SNAPSHOT VERSION (803) - Use at your own risk
[11:18:46 INFO]: Everything has finished loading! If you like our work, consider subscribing to our Patreon! <3
[11:18:46 INFO]: https://www.patreon.com/screamingsandals
[11:18:47 INFO]: [SBAHypixelify] Enabling SBAHypixelify v2.0.0-SNAPSHOT
[11:18:47 INFO]: [SBAHypixelify] Obtaining jar file from: class pronze.hypixelify.SBAHypixelify
[11:18:47 INFO]: [SBAHypixelify] pronze.hypixelify.commands.CommandManager
[11:18:47 INFO]: [SBAHypixelify] pronze.hypixelify.commands.party.PartyWarpCommand
[11:18:47 INFO]: [SBAHypixelify] pronze.hypixelify.commands.party.PartyAcceptCommand
...
[11:18:47 INFO]: [SBAHypixelify] pronze.hypixelify.lib.npclib.nms.v1_16_R3.NPC_v1_16_R3
[11:18:47 INFO]: [SBAHypixelify] pronze.hypixelify.lib.npclib.nms.v1_16_R3.packets.PacketPlayOutAnimationWrapper
[11:18:47 INFO]: [SBAHypixelify] pronze.hypixelify.lib.npclib.nms.v1_16_R3.packets.PacketPlayOutEntityHeadRotationWrapper
[11:18:47 INFO]: [SBAHypixelify] pronze.hypixelify.lib.npclib.nms.v1_16_R3.packets.PacketPlayOutEntityMetadataWrapper
[11:18:47 INFO]: [SBAHypixelify] pronze.hypixelify.lib.npclib.nms.v1_16_R3.packets.PacketPlayOutNamedEntitySpawnWrapper
[11:18:47 INFO]: [SBAHypixelify] pronze.hypixelify.lib.npclib.nms.v1_16_R3.packets.PacketPlayOutPlayerInfoWrapper
[11:18:47 INFO]: [SBAHypixelify] pronze.hypixelify.lib.npclib.nms.v1_16_R3.packets.PacketPlayOutScoreboardTeamWrapper
[11:18:47 INFO]: [SBAHypixelify] Time taken for classes scan: 195ms
[11:18:47 INFO]: [SBAHypixelify] Registering API service provider
[11:18:47 INFO]: [SBAHypixelify] Plugin has loaded!
[11:18:47 INFO]: Starting GS4 status listener
...
[11:18:47 WARN]: [SBAHypixelify] Task #498 for SBAHypixelify v2.0.0-SNAPSHOT generated an exception
java.lang.NoClassDefFoundError: org/screamingsandals/bedwars/lib/material/Item
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:3334) ~[?:?]
        at java.lang.Class.getDeclaredMethods(Class.java:2446) ~[?:?]
        at pronze.hypixelify.lib.core.auto.AutoInitializer.construct(AutoInitializer.java:160) ~[?:?]
        at pronze.hypixelify.lib.core.auto.AutoInitializer.lambda$init$16(AutoInitializer.java:121) ~[?:?]
...
Caused by: java.lang.ClassNotFoundException: org.screamingsandals.bedwars.lib.material.Item 
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[patched_1.16.5.jar:git-Paper-753]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-753]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 30 more
[11:18:47 INFO]: Done (5.068s)! For help, type "help"
[11:18:47 INFO]: Timings Reset
```

Removing just the SBAHypixelify plugin makes the problem go away.

**Comment by zlataovce** [comment]
the CI is building the plugin properly, but sba v2 is under heavy rewriting and certainly broken right now

**Comment by pronze** [comment]
BW 0.3.0 and SBA v2.0 Are not usuable atm.
