### ISSUE TITLE
Issue while running on minecraft 1.13.2

### ISSUE THREAD

**Issue by DeepFriedYeti** [pronze/SBA#132]
Whenever I start up the server with this plugin, i get some error and the shops and stuff don't get changed
My server is already running on java 11

Here's the log of error:

 Error occurred while enabling SBAHypixelify v1.4.3 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.OAK_SIGN
at java.lang.Enum.valueOf(Enum.java:240) ~[?:?]
at org.bukkit.Material.valueOf(Material.java:1) ~[minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at io.pronze.hypixelify.utils.ShopUtil.createCategories(ShopUtil.java:405) ~[?:?]
at io.pronze.hypixelify.inventories.GamesInventory.createData(GamesInventory.java:90) ~[?:?]
at io.pronze.hypixelify.inventories.GamesInventory.<init>(GamesInventory.java:66) ~[?:?]
at io.pronze.hypixelify.SBAHypixelify.onEnable(SBAHypixelify.java:154) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by DeepFriedYeti** [comment]
Anything??

**Comment by pronze** [comment]
Get the latest SBA from our jenkins! https://ci.screamingsandals.org/job/SBAHypixelify/
