### ISSUE TITLE
Could not pass event PlayerInteractEvent to BedWars v0.2.17

### ISSUE THREAD

**Issue by AlexTheKing14** [pronze/SBA#141]
Hello, I installed the plugin on my 1.17 server (with the SBA addon), I configured my map.

I start a game and when I have to choose a team with the compass, the server crashes with this error code:

```
> [09:58:25] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to BedWars v0.2.17
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:499) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:466) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:462) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1591) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.TickTask.run(SourceFile:18) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1124) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1117) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1101) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1030) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
at net.minecraft.core.NonNullList.get(SourceFile:46) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.world.inventory.Container.b(Container.java:272) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.world.inventory.Container.d(Container.java:228) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.world.inventory.Container.addSlotListener(Container.java:161) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.level.EntityPlayer.initMenu(EntityPlayer.java:545) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.bukkit.craftbukkit.v1_17_R1.entity.CraftHumanEntity.openCustomInventory(CraftHumanEntity.java:325) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.bukkit.craftbukkit.v1_17_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:303) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.screamingsandals.bedwars.lib.sgui.inventory.GuiHolder.(GuiHolder.java:88) ~[?:?]
at org.screamingsandals.bedwars.lib.sgui.SimpleInventories.openForPlayer(SimpleInventories.java:1010) ~[?:?]
at org.screamingsandals.bedwars.inventories.TeamSelectorInventory.openForPlayer(TeamSelectorInventory.java:68) ~[?:?]
at org.screamingsandals.bedwars.listener.PlayerListener.onPlayerInteract(PlayerListener.java:683) ~[?:?]
at jdk.internal.reflect.GeneratedMethodAccessor41.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:3100-Spigot-c9cea60-5182f92]
... 21 more
```

**Comment by PikachuPlays** [comment]
1.17 is not supported with SBA

**Comment by pronze** [comment]
SBA now supports 1.17, feel free to use the latest build from https://ci.screamingsandals.org/job/SBAHypixelify/
