### ISSUE TITLE
Error at startup using latest snapshot.

### ISSUE THREAD

**Issue by kerostampcrab** [pronze/SBA#158]
Using zulu-16, latest snapshot of SBA, i get the error:
```
[17:22:18 ERROR]: [org.bukkit.craftbukkit.v1_17_R1.CraftServer] Bad type on operand stack
Exception Details:
  Location:
    io/github/pronze/sba/SBA.enableLegacySupport()V @56: invokestatic
  Reason:
    Type 'org/screamingsandals/bedwars/Main' (current frame, stack[0]) is not assignable to 'org/bukkit/plugin/java/JavaPlugin'
  Current Frame:
    bci: @56
    flags: { }
    locals: { 'io/github/pronze/sba/SBA', 'java/util/concurrent/atomic/AtomicBoolean' }
    stack: { 'org/screamingsandals/bedwars/Main' }
  Bytecode:
    0000000: b800 9899 0038 bb00 9a59 03b7 009d 4cb2
    0000010: 009f 2bba 00b3 0000 b900 b702 002b b600
    0000020: ba99 001a 2ab6 008c 12bc b900 9402 00b8
    0000030: 00c0 b600 c5b8 00c8 b800 ceb1          
  Stackmap Table:
    same_frame(@59)
 initializing SBA v1.5.6-SNAPSHOT (Is it up to date?)
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    io/github/pronze/sba/SBA.enableLegacySupport()V @56: invokestatic
  Reason:
    Type 'org/screamingsandals/bedwars/Main' (current frame, stack[0]) is not assignable to 'org/bukkit/plugin/java/JavaPlugin'
  Current Frame:
    bci: @56
    flags: { }
    locals: { 'io/github/pronze/sba/SBA', 'java/util/concurrent/atomic/AtomicBoolean' }
    stack: { 'org/screamingsandals/bedwars/Main' }
  Bytecode:
    0000000: b800 9899 0038 bb00 9a59 03b7 009d 4cb2
    0000010: 009f 2bba 00b3 0000 b900 b702 002b b600
    0000020: ba99 001a 2ab6 008c 12bc b900 9402 00b8
    0000030: 00c0 b600 c5b8 00c8 b800 ceb1          
  Stackmap Table:
    same_frame(@59)

        at io.github.pronze.sba.SBA_BukkitImpl.onLoad(SBA_BukkitImpl.java:98) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:408) ~[patched_1.17.1.jar:git-Purpur-1305]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286) ~[patched_1.17.1.jar:git-Purpur-1305]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[patched_1.17.1.jar:git-Purpur-1305]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1305]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

Which seems to relate to SBA.

Later i get this error:
```
[17:26:17 ERROR]: Error occurred while enabling SBA v1.5.6-SNAPSHOT (Is it up to date?)
java.lang.UnsupportedOperationException: Plugin must be loaded before enabling!
        at io.github.pronze.sba.SBA_BukkitImpl.onEnable(SBA_BukkitImpl.java:467) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Purpur-1305]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1305]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1305]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:527) ~[patched_1.17.1.jar:git-Purpur-1305]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:441) ~[patched_1.17.1.jar:git-Purpur-1305]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:712) ~[patched_1.17.1.jar:git-Purpur-1305]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Purpur-1305]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[patched_1.17.1.jar:git-Purpur-1305]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1305]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[17:26:17 INFO]: [SBA] Disabling SBA v1.5.6-SNAPSHOT
[17:26:17 ERROR]: Error occurred while disabling SBA v1.5.6-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "io.github.pronze.sba.SBA.disable()" because "this.pluginContainer" is null
        at io.github.pronze.sba.SBA_BukkitImpl.onDisable(SBA_BukkitImpl.java:476) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.17.1.jar:git-Purpur-1305]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.17.1.jar:git-Purpur-1305]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.17.1.jar:git-Purpur-1305]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.1.jar:git-Purpur-1305]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1305]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:527) ~[patched_1.17.1.jar:git-Purpur-1305]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:441) ~[patched_1.17.1.jar:git-Purpur-1305]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:712) ~[patched_1.17.1.jar:git-Purpur-1305]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Purpur-1305]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[patched_1.17.1.jar:git-Purpur-1305]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1305]
        at java.lang.Thread.run(Thread.java:831) [?:?]

```

I am on Arch Linux (KDE Plasma), using Purpur 1.17.1 as my server software. Didn't happen before, suddenly started.

**Comment by pronze** [comment]
Try using the latest snapshot, with Bedwars 0.2.18 version. Make sure you have java 11.

**Comment by kerostampcrab** [comment]
Yeah sorry, i was using Bedwars 0.3. I switched to 0.2.20 and it works now.
