### ISSUE TITLE
Error enabling SBA v1.5.5 with 0.3.0 build 812

### ISSUE THREAD

**Issue by SilverSeed93** [pronze/SBA#171]
SBA will not load. 

[13:04:05 INFO]: This server is running Paper version git-Paper-146 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: ed1dc27)

[13:05:07 INFO]: =====================  by ScreamingSandals <Misat11, Iamceph, Pronze>
[13:05:07 INFO]: + Screaming BedWars +  Version: 0.3.0-SNAPSHOT FREE
[13:05:07 INFO]: =====================  SNAPSHOT VERSION (812) - Use at your own risk
[13:05:07 INFO]: [BW] Found Vault
[13:05:07 INFO]: Everything has finished loading! If you like our work, consider subscribing to our Patreon! <3
[13:05:07 INFO]: https://www.patreon.com/screamingsandals
[13:05:07 INFO]: [PlaceholderAPI] Successfully registered expansion: bedwars
[13:05:07 INFO]: [SBA] Enabling SBA v1.5.5
[13:05:07 ERROR]: Error occurred while enabling SBA v1.5.5 (Is it up to date?)
java.lang.UnsupportedOperationException: Plugin must be loaded before enabling!
        at io.github.pronze.sba.SBA_BukkitImpl.onEnable(SBA_BukkitImpl.java:427) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-146]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-146]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-146]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:529) ~[patched_1.17.1.jar:git-Paper-146]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:443) ~[patched_1.17.1.jar:git-Paper-146]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639) ~[patched_1.17.1.jar:git-Paper-146]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-146]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-146]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-146]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[13:05:07 INFO]: [SBA] Disabling SBA v1.5.5
[13:05:07 ERROR]: Error occurred while disabling SBA v1.5.5 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "io.github.pronze.sba.SBA.disable()" because "this.pluginContainer" is null
        at io.github.pronze.sba.SBA_BukkitImpl.onDisable(SBA_BukkitImpl.java:436) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.17.1.jar:git-Paper-146]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.17.1.jar:git-Paper-146]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.17.1.jar:git-Paper-146]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.1.jar:git-Paper-146]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-146]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:529) ~[patched_1.17.1.jar:git-Paper-146]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:443) ~[patched_1.17.1.jar:git-Paper-146]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639) ~[patched_1.17.1.jar:git-Paper-146]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-146]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-146]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-146]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by DeathGOD7** [comment]
Use the stable one : SBA 1.5.5 and SBW 0.2.18
