### ISSUE TITLE
Error enabling SBA v1.5.5 with 0.2.19

### ISSUE THREAD

**Issue by SilverSeed93** [pronze/SBA#172]
SBA will not enable. Plugin error information seems to be reading version incorrectly. Says I'm running 1.5.0 when I am running 1.5.5.

[13:11:03 INFO]: [BedWars] Enabling BedWars v0.2.19
[13:11:03 INFO]: [BedWars] Successfully loaded messages for BedWars! Language: English
[13:11:03 INFO]: [BedWars] Loading statistics from YAML-File ...
[13:11:03 INFO]: [PlaceholderAPI] Successfully registered expansion: bedwars
[13:11:03 INFO]: =====================  by ScreamingSandals <Misat11, Iamceph, Pronze>
[13:11:03 INFO]: + Screaming BedWars +  Version: 0.2.19 FREE
[13:11:03 INFO]: =====================  STABLE VERSION
[13:11:03 INFO]: [BW] Found Vault
[13:11:03 INFO]: Everything is loaded! If you like our work, consider visiting our Patreon! <3
[13:11:03 INFO]: https://www.patreon.com/screamingsandals
[13:11:03 INFO]: [SBA**] Enabling SBA v1.5.5**
[13:11:04 ERROR]: ======PLUGIN ERROR===========
[13:11:04 ERROR]: Plugin: SBA is being disabled for the following error:
[13:11:04 ERROR]: You need ScreamingBedWars v0.2.18 to run **SBA v1.5.0**
[13:11:04 ERROR]: Get the latest version from here: https://www.spigotmc.org/resources/screaming-bedwars-1-9-1-16.63714/
[13:11:04 ERROR]: =============================
[13:11:04 INFO]: [SBA] Disabling SBA v1.5.5
[13:11:04 INFO]: No updates found
[13:11:04 ERROR]: Failed to initialize the command manager
[13:11:04 INFO]: [SBA] Disabling SBA v1.5.5
[13:11:04 ERROR]: Error occurred while enabling SBA v1.5.5 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register io.github.pronze.sba.service.HealthIndicatorService@5980e7a6 while not enabled
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:653) ~[patched_1.17.1.jar:git-Paper-146]
        at io.github.pronze.sba.SBA.registerListener(SBA.java:187) ~[?:?]
        at io.github.pronze.sba.service.HealthIndicatorService.postEnabled(HealthIndicatorService.java:52) ~[?:?]
        at io.github.pronze.sba.SBA_BukkitImpl$5.run(SBA_BukkitImpl.java:141) ~[?:?]
        at io.github.pronze.lib.screaminglib.utils.ControllableImpl.postEnable(ControllableImpl.java:57) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at io.github.pronze.lib.screaminglib.utils.ControllableImpl.postEnable(ControllableImpl.java:55) ~[?:?]
        at io.github.pronze.sba.SBA_BukkitImpl.onEnable(SBA_BukkitImpl.java:431) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-146]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-146]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-146]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:529) ~[patched_1.17.1.jar:git-Paper-146]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:443) ~[patched_1.17.1.jar:git-Paper-146]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639) ~[patched_1.17.1.jar:git-Paper-146]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-146]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-146]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-146]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by DeathGOD7** [comment]
> SBA will not enable. Plugin error information seems to be reading the version incorrectly. Says I'm running 1.5.0 when I am running 1.5.5.

It's a typo error. And SBW 0.2.19 doesn't support the 1.5.5 version of SBA.
Either use 0.2.18 SBW and use 1.17 or use 1.5.6 snapshot for 0.2.19 (for support of 1.17.1).

**Comment by SilverSeed93** [comment]
Thank you. I was simply confused with the typo, it literally says two different things there in that output.
