### ISSUE TITLE
Bug with the lastet snapshot of SBA

### ISSUE THREAD

**Issue by Lun3z** [pronze/SBA#173]
Error code : 
[18:34:58 ERROR]: Error occurred while enabling SBA v1.5.6-SNAPSHOT (Is it up to date?)
java.lang.IllegalAccessError: failed to access class io.leangen.geantyref.AnnotatedArrayTypeImpl from class io.leangen.geantyref.GenericTypeReflector (io.leangen.geantyref.AnnotatedArrayTypeImpl is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @45bec623; io.leangen.geantyref.GenericTypeReflector is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @1608aa85)
        at io.leangen.geantyref.GenericTypeReflector.annotate(GenericTypeReflector.java:906) ~[?:?]
        at io.leangen.geantyref.GenericTypeReflector.annotate(GenericTypeReflector.java:812) ~[?:?]
        at io.leangen.geantyref.GenericTypeReflector.annotate(GenericTypeReflector.java:823) ~[?:?]
        at io.leangen.geantyref.TypeToken.get(TypeToken.java:49) ~[?:?]
        at io.github.pronze.lib.cloud.arguments.parser.StandardParserRegistry.<init>(StandardParserRegistry.java:134) ~[?:?]
        at io.github.pronze.lib.cloud.CommandManager.<init>(CommandManager.java:93) ~[?:?]
        at io.github.pronze.lib.cloud.bukkit.BukkitCommandManager.<init>(BukkitCommandManager.java:121) ~[?:?]
        at io.github.pronze.lib.cloud.paper.PaperCommandManager.<init>(PaperCommandManager.java:89) ~[?:?]
        at io.github.pronze.sba.commands.CommandManager.onEnable(CommandManager.java:54) ~[?:?]
        at io.github.pronze.sba.SBA_BukkitImpl$21.run(SBA_BukkitImpl.java:310) ~[?:?]
        at io.github.pronze.lib.screaminglib.utils.ControllableImpl.enable(ControllableImpl.java:50) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at io.github.pronze.lib.screaminglib.utils.ControllableImpl.enable(ControllableImpl.java:48) ~[?:?]
        at io.github.pronze.sba.SBA_BukkitImpl.onEnable(SBA_BukkitImpl.java:517) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by DeathGOD7** [comment]
BedWars and SBA (Build) version?
