### ISSUE TITLE
Plugin Errors

### ISSUE THREAD

**Issue by MCJiaoLong** [pronze/SBA#187]
server:
spigot-1.16.5
The plugin versions are up to date

[14:54:17] [Server thread/INFO]: [SBA] Loading SBA v1.5.6-SNAPSHOT
[14:54:17] [Server thread/ERROR]: org/screamingsandals/bedwars/Main initializing SBA v1.5.6-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: org/screamingsandals/bedwars/Main
        at io.github.pronze.sba.SBA_BukkitImpl.onLoad(SBA_BukkitImpl.java:211) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:388) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:185) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: org.screamingsandals.bedwars.Main
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 6 more

**Comment by MCJiaoLong** [comment]
Is anybody there?
