### ISSUE TITLE
Problem Loading Plugin

### ISSUE THREAD

**Issue by SkeppyFan123** [pronze/SBA#190]
Hi,
When i try to load the plugin it said:
[01:39:00 ERROR]: Error occurred while enabling SBA v1.5.5 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register io.github.pronze.sba.service.HealthIndicatorService@66378be5 while not enabled
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:653) ~[patched_1.17.1.jar:git-Paper-239]
	at io.github.pronze.sba.SBA.registerListener(SBA.java:187) ~[SBA-1.5.5.jar:?]
	at io.github.pronze.sba.service.HealthIndicatorService.postEnabled(HealthIndicatorService.java:52) ~[SBA-1.5.5.jar:?]
	at io.github.pronze.sba.SBA_BukkitImpl$5.run(SBA_BukkitImpl.java:141) ~[SBA-1.5.5.jar:?]
	at io.github.pronze.lib.screaminglib.utils.ControllableImpl.postEnable(ControllableImpl.java:57) ~[SBA-1.5.5.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at io.github.pronze.lib.screaminglib.utils.ControllableImpl.postEnable(ControllableImpl.java:55) ~[SBA-1.5.5.jar:?]
	at io.github.pronze.sba.SBA_BukkitImpl.onEnable(SBA_BukkitImpl.java:431) ~[SBA-1.5.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-239]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-239]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-239]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535) ~[patched_1.17.1.jar:git-Paper-239]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449) ~[patched_1.17.1.jar:git-Paper-239]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:725) ~[patched_1.17.1.jar:git-Paper-239]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-239]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1212) ~[patched_1.17.1.jar:git-Paper-239]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-239]
	at java.lang.Thread.run(Thread.java:831) [?:?]

Can you tell me a way to fix this?

**Comment by FireFall-YT** [comment]
Jenkins is shutted down.
