### ISSUE TITLE
Plugin tryed to register while not enabled

### ISSUE THREAD

**Issue by HackerBanane** [pronze/SBA#196]
When I start the Server the plugin doesn't work and in the Server log is this error:

Error occurred while enabling SBA v1.5.5 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register io.github.pronze.sba.service.HealthIndicatorService@2ba61f60 while not enabled
    at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:653) ~[server.jar:git-Paper-282]
    at io.github.pronze.sba.SBA.registerListener(SBA.java:187) ~[SBA-1.5.5.jar:?]
    at io.github.pronze.sba.service.HealthIndicatorService.postEnabled(HealthIndicatorService.java:52) ~[SBA-1.5.5.jar:?]
    at io.github.pronze.sba.SBA_BukkitImpl$5.run(SBA_BukkitImpl.java:141) ~[SBA-1.5.5.jar:?]
    at io.github.pronze.lib.screaminglib.utils.ControllableImpl.postEnable(ControllableImpl.java:57) ~[SBA-1.5.5.jar:?]
    at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
    at io.github.pronze.lib.screaminglib.utils.ControllableImpl.postEnable(ControllableImpl.java:55) ~[SBA-1.5.5.jar:?]
    at io.github.pronze.sba.SBA_BukkitImpl.onEnable(SBA_BukkitImpl.java:431) ~[SBA-1.5.5.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Paper-282]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[server.jar:git-Paper-282]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[server.jar:git-Paper-282]
    at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535) ~[server.jar:git-Paper-282]
    at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449) ~[server.jar:git-Paper-282]
    at org.bukkit.craftbukkit.v1_17_R1.CraftServer.reload(CraftServer.java:970) ~[server.jar:git-Paper-282]
    at org.bukkit.Bukkit.reload(Bukkit.java:769) ~[server.jar:git-Paper-282]
    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[server.jar:git-Paper-282]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[server.jar:git-Paper-282]
    at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838) ~[server.jar:git-Paper-282]
    at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2257) ~[server.jar:git-Paper-282]
    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2068) ~[server.jar:git-Paper-282]
    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2049) ~[server.jar:git-Paper-282]
    at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[server.jar:git-Paper-282]
    at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6) ~[server.jar:git-Paper-282]
    at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[server.jar:git-Paper-282]
    at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server.jar:git-Paper-282]
    at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[server.jar:git-Paper-282]
    at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[server.jar:git-Paper-282]
    at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418) ~[server.jar:git-Paper-282]
    at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[server.jar:git-Paper-282]
    at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[server.jar:git-Paper-282]
    at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396) ~[server.jar:git-Paper-282]
    at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389) ~[server.jar:git-Paper-282]
    at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[server.jar:git-Paper-282]
    at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1367) ~[server.jar:git-Paper-282]
    at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1278) ~[server.jar:git-Paper-282]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[server.jar:git-Paper-282]
    at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by RealSlovenianGamer** [comment]
What's your server version and java version?

**Comment by HackerBanane** [comment]
The Server is on paper 1.17.1 and my java version is 16.

**Comment by RealSlovenianGamer** [comment]
**Hello!**
I've had the same problem with java.
To resolve the issue uninstall java completely and install it again but the **11 version**. This solved the issue for me. If still not working try using other server platforms. (Also **why** tf would any1 want 1.17 bedwars?)
Hope it helps,
_SlovenianGamer_

**Comment by HackerBanane** [comment]
I tried to use v11 but the server didnt start. Its a server for me and some friends and we wanna play bedwars on a private server. Mainly we use it for survival so its on 1.17. I tried to use an old pvp plugin but sadly it didnt worked. I will setup a new server only for pvp in 1.8.9.
