### ISSUE TITLE
Plugin Errors when I use it

### ISSUE THREAD

**Issue by KittenPixel-cell** [pronze/SBA#222]
<html>
<body>

[17:55:20] [Server thread/ERROR]: ======PLUGIN ERROR===========
--
38 | [17:55:20] [Server thread/ERROR]: Plugin: SBA is being disabled for the following error:
39 | [17:55:20] [Server thread/ERROR]: You need ScreamingBedWars v0.2.18 to run SBA v1.5.0
40 | [17:55:20] [Server thread/ERROR]: Get the latest version from here: https://www.spigotmc.org/resources/screaming-bedwars-1-9-1-16.63714/
41 | [17:55:20] [Server thread/ERROR]: =============================
42 | [17:55:20] [Server thread/INFO]: [SBA] Disabling SBA v1.5.5
43 | [17:55:20] [Server thread/ERROR]: Failed to initialize the command manager
44 | [17:55:20] [Server thread/INFO]: [SBA] Disabling SBA v1.5.5
45 | [17:55:20] [Server thread/ERROR]: Error occurred while enabling SBA v1.5.5 (Is it up to date?)
46 | org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register io.github.pronze.sba.service.HealthIndicatorService@24118e54 while not enabled
47 | at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:657) ~[patched_1.17.1.jar:git-Paper-409]
48 | at io.github.pronze.sba.SBA.registerListener(SBA.java:187) ~[SBA-1.5.5.jar:?]
49 | at io.github.pronze.sba.service.HealthIndicatorService.postEnabled(HealthIndicatorService.java:52) ~[SBA-1.5.5.jar:?]
50 | at io.github.pronze.sba.SBA_BukkitImpl$5.run(SBA_BukkitImpl.java:141) ~[SBA-1.5.5.jar:?]
51 | at io.github.pronze.lib.screaminglib.utils.ControllableImpl.postEnable(ControllableImpl.java:57) ~[SBA-1.5.5.jar:?]
52 | at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
53 | at io.github.pronze.lib.screaminglib.utils.ControllableImpl.postEnable(ControllableImpl.java:55) ~[SBA-1.5.5.jar:?]
54 | at io.github.pronze.sba.SBA_BukkitImpl.onEnable(SBA_BukkitImpl.java:431) ~[SBA-1.5.5.jar:?]
55 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-409]
56 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-409]
57 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-409]
58 | at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-409]
59 | at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-409]
60 | at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-409]
61 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-409]
62 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-409]
63 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-409]
64 | at java.lang.Thread.run(Thread.java:831) ~[?:?]

</body>
</html>[17:55:20] [Server thread/ERROR]: ======PLUGIN ERROR===========
[17:55:20] [Server thread/ERROR]: Plugin: SBA is being disabled for the following error:
[17:55:20] [Server thread/ERROR]: You need ScreamingBedWars v0.2.18 to run SBA v1.5.0
[17:55:20] [Server thread/ERROR]: Get the latest version from here: https://www.spigotmc.org/resources/screaming-bedwars-1-9-1-16.63714/
[17:55:20] [Server thread/ERROR]: =============================
[17:55:20] [Server thread/INFO]: [SBA] Disabling SBA v1.5.5
[17:55:20] [Server thread/ERROR]: Failed to initialize the command manager
[17:55:20] [Server thread/INFO]: [SBA] Disabling SBA v1.5.5
[17:55:20] [Server thread/ERROR]: Error occurred while enabling SBA v1.5.5 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register io.github.pronze.sba.service.HealthIndicatorService@24118e54 while not enabled
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:657) ~[patched_1.17.1.jar:git-Paper-[40](https://aternos.org/log/#L40)9]
	at io.github.pronze.sba.SBA.registerListener(SBA.java:187) ~[SBA-1.5.5.jar:?]
	at io.github.pronze.sba.service.HealthIndicatorService.postEnabled(HealthIndicatorService.java:52) ~[SBA-1.5.5.jar:?]
	at io.github.pronze.sba.SBA_BukkitImpl$5.run(SBA_BukkitImpl.java:1[41](https://aternos.org/log/#L41)) ~[SBA-1.5.5.jar:?]
	at io.github.pronze.lib.screaminglib.utils.ControllableImpl.postEnable(ControllableImpl.java:57) ~[SBA-1.5.5.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at io.github.pronze.lib.screaminglib.utils.ControllableImpl.postEnable(ControllableImpl.java:55) ~[SBA-1.5.5.jar:?]
	at io.github.pronze.sba.SBA_BukkitImpl.onEnable(SBA_BukkitImpl.java:[43](https://aternos.org/log/#L43)1) ~[SBA-1.5.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-409]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-409]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-409]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-409]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:[47](https://aternos.org/log/#L47)5) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-409]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Comment by Harry-CODE-HE** [comment]
plugin is discontinued need to move to a different plugin now
